### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by xmunoz** [Cronenbrogues/cronenbroguelike#36] opened 2020-12-20 23:15 UTC
```
You die.

...

A desk i̊s st̾rewn͊ with sheaves of paper. Little of senͨse is written there̕.
There is a(n) F͕ish Man sl̐obbering in t̕he corner.
Exits are͢ east, by clìmbing a y̌awning s̸phinct̊er.

> go east
You proc͘ee͟d east.
Traceback (most recent call last):
  File "demo.py", line 107, in <module>
    adventurelib.start()
  File "/home/user/workspace/cronenbroguelike/venv/lib/python3.8/site-packages/adventurelib.py", line 627, in start
    _handle_command(cmd)
  File "/home/user/workspace/cronenbroguelike/venv/lib/python3.8/site-packages/adventurelib.py", line 600, in _handle_command
    func(**args)
  File "<string>", line 4, in wrapped
  File "/home/user/workspace/cronenbroguelike/cronenbroguelike/commands.py", line 52, in go
    G.player.current_room.on_exit()
  File "/home/user/workspace/cronenbroguelike/engine/room.py", line 91, in on_exit
    self._characters.remove(_G.player)
  File "/home/user/workspace/cronenbroguelike/venv/lib/python3.8/site-packages/adventurelib.py", line 292, in remove
    super().remove(item)
KeyError: <engine.actor.Actor object at 0x7f47a1a1d040>
```

**Comment by flosincapite** [comment] 2020-12-22 04:17
I can't reproduce this. Can you provide a fuller log?

**Comment by xmunoz** [comment] 2020-12-23 03:09
Nope, sorry :/

**Comment by flosincapite** [comment] 2020-12-28 21:49
Closing since we can't reproduce.

**Closed as completed by flosincapite** 2020-12-28 21:49 UTC
